# Generated by Django 4.0 on 2022-01-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_dic_order_ico_order_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_code',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
